# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieDBApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieDBApp

  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  
  # add star rating system
  pod 'HCSStarRatingView', '~> 1.5'

  # used in the rating system
  pod 'Firebase/Database'

end
